default: &default
  enabled: true
  repository:
    type: merritt
    domain: merritt-dev.example.org
    endpoint: "http://sword-dev.example.org:39001/mrtsword/collection/test"
    username: "test"
    password: "test"
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  abbreviation: "DataONE"
  short_name: "DataONE"
  long_name: "DataONE"
  full_domain: "example-dev.example.org"
  domain_regex: "example-dev.example.org$"
  tenant_id: dataone
  identifier_service:
    shoulder: "doi:10.5072/FK2"
    account: test
    password: test
    id_scheme: doi
    owner: null
  authentication:
    strategy: google
  default_license: cc0
  dash_logo_after_tenant: false

development:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    type: merritt
    domain: merritt-stage.example.org
    endpoint: "http://sword-stg.example.org:39001/mrtsword/collection/stage"
    username: "test"
    password: "test"
  full_domain: "example-stg.example.org"
  domain_regex: "example-stg.example.org$"
  tenant_id: dataone
  identifier_service:
    shoulder: "doi:10.5072/FK2"
    account: test
    password: test
    owner: null
    id_scheme: doi
  authentication:
    strategy: google
  default_license: cc0

production:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here
