defaults: &defaults
  mapper:
    metadata_mapping: datacite_geoblacklight
  db: none
  source:
    protocol: 'Merritt Atom'
    tenant_path: config/tenants/ucsf.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5ng4nz1'
  index:
    adapter: Dash2
    db_config_path: config/database.yml
    tenant_path: config/tenants/ucop.yml
    id_mode: always_mint

test:
  <<: *defaults

development:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
  index:
    adapter: Dash2
    db_config_path: config/database.yml
    id_mode: always_update


