sources:
# DataUP
#  - tenant_path: config/tenants/dataone.yml
#    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5222s39'
  - tenant_path: config/tenants/ucb.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5q82t8x'
  - tenant_path: config/tenants/uci.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5fr19qh'
  - tenant_path: config/tenants/ucla.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5tm8r6v'
  - tenant_path: config/tenants/ucm.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5sv2b3c'
  - tenant_path: config/tenants/ucsc.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5t16hvv'
  - tenant_path: config/tenants/ucsf.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m52j8gvj'
  - tenant_path: config/tenants/ucsf.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5ng4nz1'
  - tenant_path: config/tenants/ucop.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5v13jxb'
  - tenant_path: config/tenants/dataone.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5709fmd'
index:
  db_config_path: config/database.yml
  tenant_override: config/tenants/ucop.yml
