sources:
# LBNL test
  - tenant_path: config/tenants/lbnl.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m50s13nf'
index:
  db_config_path: config/database.yml
users_path: config/dash1_records_users.txt
