defaults: &defaults
  mapper:
    metadata_mapping: datacite_geoblacklight
  index:
    adapter: Dash2
    db_config_path: config/database.yml
  db:
    adapter: sqlite3
    database: ':memory:'
    pool: 5
    timeout: 5000
  source:
    protocol: 'Merritt Atom'
    tenant_path: config/tenants/dataone.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5709fmd'

test:
  <<: *defaults

development:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
