users_path: config/dash1_records_users.txt
index:
  db_config_path: config/database.yml
sources:
# UCR
  - tenant_path: config/tenants/ucr.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5jt2v2m'
# UCM SSCZO
  - tenant_path: config/tenants/ucm_ssczo.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5sv2b3c'
# UCM
  - tenant_path: config/tenants/ucm.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5b00k0h'
# UCLA
  - tenant_path: config/tenants/ucla.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5tm8r6v'
# UCSC
  - tenant_path: config/tenants/ucsc.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5t16hvv'
# UCOP
  - tenant_path: config/tenants/ucop.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5v13jxb'
# UCB
  - tenant_path: config/tenants/ucb.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5q82t8x'
# UCSF Library (ucsf_lib_datashare)
  - tenant_path: config/tenants/ucsf.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m52j8gvj'
# UCSF legacy (ucsf_datashare)
  - tenant_path: config/tenants/ucsf_legacy.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5ng4nz1'
# UCI
  - tenant_path: config/tenants/uci.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5fr19qh'
# DataONE
  - tenant_path: config/tenants/dataone.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5709fmd'
# DataUP
  - tenant_path: config/tenants/dataone.yml
    feed_uri: 'https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5222s39'
