defaults: &defaults
  mapper:
    metadata_mapping: datacite_geoblacklight
  index:
    adapter: Dash2
    db_config_path: config/database.yml
  db:
    adapter: sqlite3
    database: ':memory:'
    pool: 5
    timeout: 5000

test:
  <<: *defaults

development:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
