- :tenant: ucla
  :doi: 10.5072/FK2571DT1Q
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucla
  :doi: 10.5072/FK2DN4515R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucla
  :doi: 10.5072/FK2JD4VT9M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2C829W2Q
  :stash_version: 3
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2514191H
  :stash_version: 2
  :merritt_version: 1
- :tenant: ucop
  :doi: 10.5072/FK2TD9TF22
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2WQ00B9V
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2FT8KQ45
  :stash_version: 4
  :merritt_version: 5
- :tenant: ucop
  :doi: 10.5072/FK2D79BG48
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2NP22P7K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2SF2SH37
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK21Z46Z1S
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK29G5NK0N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2PN93M1T
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK26Q1ZN6Q
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2Z60J66J
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2KW5DP6C
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2VD6V92P
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK27P90J81
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2CC10Z8G
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2MW2FK4F
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2WD3W618
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK28K7B23J
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2J38RP0X
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2251MQ8S
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK29K4BZ36
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2K35SJ96
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2ZC7Z04S
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2BK1CV18
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2QV3J84H
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK24170443
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2CJ8DR0M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2N29VC00
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2WH2KK7C
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK28S4QT76
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2DJ5FN2R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2SQ8WP1G
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2XG9MG56
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK29S1RQ79
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2K64GZ3K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2TQ5XK1K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2377C083
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK27082T36
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2GF0T193
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2VQ2ZG05
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2474CX1M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2CN7445N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2N58JR3J
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK29W0G435
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2XP71812
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2KD1WQ86
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2ZP4252P
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2TX3BB8N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2BV7H110
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2MC8XM82
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2VT1NV47
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK24B33933
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2HM57Q3B
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2833T36W
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2S17ZZ0Q
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2930V060
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK21J9DD18
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2JM28M7H
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2T150V1R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK22J6F88H
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2B27VW7X
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2KH0M41H
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2V121R0B
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2ZS2RJ3S
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2794602N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2GQ6X69C
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK20R9S84R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2R78BT7P
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK28916W5V
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2NG4NX32
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2X063H9G
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK25H7HZ9N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2DZ08658
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2PG1PT0M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK22R3V25G
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2B56K91R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2KP80W7C
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2V69FH5Q
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK27D2WC7T
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2GX4B02P
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2RF5RM2M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK24M96G2V
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2D50N27K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2NP22P62
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2X34SX3F
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2F47P009
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2PK0D644
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2Z31TT5K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2BC40258
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2KS6Q89F
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2V984X0M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK27M0951N
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2RJ4G064
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2H131C7M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2125WF33
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK28K7B221
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2J10289R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2SJ1GW58
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2222XB4Q
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK2D79BG27
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2HX1BW09
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucop
  :doi: 10.5072/FK2348NM6M
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.20200/embxxx01
  :stash_version: 1
  :merritt_version: 4
- :tenant: ucb
  :doi: 10.20200/hijxxx0004
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.20200/bigxxxxx2
  :stash_version: 4
  :merritt_version: 9
- :tenant: ucb
  :doi: 10.20200/xxxxxxxxx20
  :stash_version: 4
  :merritt_version: 3
- :tenant: ucb
  :doi: 10.20200/xxxxxxxxx15
  :stash_version: 4
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.20200/hij1000106
  :stash_version: 1
  :merritt_version: 7
- :tenant: ucb
  :doi: 10.5072/FK29G5NJ9T
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2K07357K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2Z897K8B
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK26Q1ZN56
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2QR4TW00
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2G73D84G
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK23X88R28
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucb
  :doi: 10.5072/FK2H70F52J
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2WH2KK6V
  :stash_version: 1
  :merritt_version: 3
- :tenant: ucb
  :doi: 10.5072/FK2154KT75
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2DF6R77V
  :stash_version: 1
  :merritt_version: 2
