- :tenant: ucm
  :doi: 10.5072/FK2K64GZ22
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucop
  :doi: 10.5072/FK20005G51
  :stash_version: 3
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK26H4JV9R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2V69FH67
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucb
  :doi: 10.5072/FK2MS3R64F
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK25141188
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2183976K
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2WH2KM1R
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2J67G24F
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2NZ85V9W
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2SQ8WP5J
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2XG9MG98
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK25X2BJ51
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2280B413
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2ZG6NC6T
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2BP0377T
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2M61HV9S
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2GF0T22Z
  :stash_version: 1
  :merritt_version: 2
- :tenant: ucsf
  :doi: 10.5072/FK2QZ27P1F
  :stash_version: 1
  :merritt_version: 2
